application: striped-botany-711
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|png|jpg|JPG))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|JPG)$

- url: /css/(.*\.(css))$
  static_files: static/css/\1
  upload: static/css/.*\.(css)$

- url: /js/(.*\.(js))$
  static_files: static/js/\1
  upload: static/js/.*\.(js)$

- url: /css/(.*\.(map))$
  static_files: static/css/\1
  upload: static/css/.*\.(map)$

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /about.html
  static_files: static/about.html
  upload: static/about.html

libraries:
- name: webapp2
  version: "2.5.2"
